### ISSUE TITLE
Quick start code from the website not working?

### ISSUE THREAD

**Issue by tintin10q** [accounts-js/accounts#1099]
# Bug report

When I try to run the quickstart code from the website it doesn't work, Multiple code sections do not work for me I must be doing something wrong. 

## Describe the bug

When I try to run https://www.accountsjs.com/docs/getting-started#usage-with-an-existing-graphql-server with Node.js v14.15.4. it first complains about the  `as any` on line 56.
``` 
    } as any)
      ^

SyntaxError: missing ) after argument list
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1092:10)
```

Removing `as any` and trying to run it I get
```
(node:8956) UnhandledPromiseRejectionWarning: Error: There can be only one type named "Query".
There can be only one type named "Mutation".
There can be only one directive named "auth".
    at assertValidSDL (C:\Projects\auth-server\node_modules\graphql\validation\validate.js:108:11)
    at Object.buildASTSchema (C:\Projects\auth-server\node_modules\graphql\utilities\buildASTSchema.js:71:34)
    at Object.buildSchemaFromTypeDefinitions (C:\Projects\auth-server\node_modules\apollo-server-core\node_modules\graphql-tools\dist\generate\buildSchemaFromTypeDefinitions.js:25:28)
    at Object.makeExecutableSchema (C:\Projects\auth-server\node_modules\apollo-server-core\node_modules\graphql-tools\dist\makeExecutableSchema.js:26:29)
    at ApolloServer.initSchema (C:\Projects\auth-server\node_modules\apollo-server-core\dist\ApolloServer.js:259:49)
    at new ApolloServerBase (C:\Projects\auth-server\node_modules\apollo-server-core\dist\ApolloServer.js:159:30)
    at new ApolloServer (C:\Projects\auth-server\node_modules\apollo-server-express\dist\ApolloServer.js:60:9)
    at new ApolloServer (C:\Projects\auth-server\node_modules\apollo-server\dist\index.js:32:9)
    at C:\Projects\auth-server\index1.js:48:26
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
(Use `node --trace-warnings ...` to show where the warning was created)
(node:8956) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not
 handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (r
ejection id: 1)
(node:8956) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
```

## To Reproduce

Steps to reproduce the behavior

Run the code from the quickstart -> https://www.accountsjs.com/docs/getting-started#usage-with-an-existing-graphql-server

## Expected behavior

The quickstart code should start up the account server and merge the typedefs without problems

## System information

- Version of accounts-js: [0.30.0]

## Aditional info

I don't know if this is important but I am starting up the code with `node -r esm index1.js`
The `-r esm` is to be able to use import statements see https://stackoverflow.com/questions/47277887/node-experimental-modules-requested-module-does-not-provide-an-export-named

But I don't think this is the cause of the issue.

**Comment by tintin10q** [comment]
Adding `extend` to `type query` and `type mutation`  and removing `directive @auth on FIELD_DEFINITION | OBJECT` from the typedevs resolves the merging issues but then it gives
`UnhandledPromiseRejectionWarning: TypeError: Class constructor SchemaDirectiveVisitor cannot be invoked without 'new'`

However adding new gives 
```
(node:8748) UnhandledPromiseRejectionWarning: TypeError: accounts.schemaDirectives is not a constructor
    at C:\Projects\the wall\auth-server\index1.js:53:13
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
(Use `node --trace-warnings ...` to show where the warning was created)
(node:8748) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not
 handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (r
ejection id: 1)
(node:8748) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
```

**Comment by pradel** [comment]
> it first complains about the as any on line 56.
We use typescript for the examples so you will need to remove the types annotations in order to make it work.

The guide is actually outdated and needs to be updated.. I saw you opened a discussion so let's move the debugging there :)
