### ISSUE TITLE
@accounts/magic-link being required even if you're not using it

### ISSUE THREAD

**Issue by acomito** [accounts-js/accounts#1156]
So happy to see @accounts/magic-link implemented!!!

But I think it seems to be required that you install it even if you're not using it?

I just freshly installed accountsjs and it seems to be looking for it.

**Comment by pradel** [comment]
can you paste the code you are using so I can have a look?

**Comment by acomito** [comment]
Sorry for the delay @pradel 

```

  node_modules/@accounts/server/lib/types/email-templates-type.d.ts:8:5
    8     magicLink: EmailTemplateType;
          ~~~~~~~~~
    'magicLink' is declared here.

    at createTSError (/Users/a/Desktop/web-dev/freelance/a/new/backend/node_modules/ts-node/src/index.ts:618:12)
    at reportTSError (/Users/anthony/Desktop/web-dev/freelance/a/new/backend/node_modules/ts-node/src/index.ts:622:19)
    at getOutput (/Users/a/Desktop/web-dev/freelance/a/new/backend/node_modules/ts-node/src/index.ts:809:36)
    at Object.compile (/Users/a/Desktop/web-dev/freelance/a/new/backend/node_modules/ts-node/src/index.ts:1111:30)
    at Module.m._compile (/Users/a/Desktop/web-dev/freelance/apaphani/new/backend/node_modules/ts-node/src/index.ts:1224:30)
    at Module._extensions..js (internal/modules/cjs/loader.js:1092:10)
    at Object.require.extensions.<computed> [as .ts] (/Users/a/Desktop/web-dev/freelance/a/new/backend/node_modules/ts-node/src/index.ts:1228:12)
    at Module.load (internal/modules/cjs/loader.js:928:32)
    at Function.Module._load (internal/modules/cjs/loader.js:769:14)
    at Module.require (internal/modules/cjs/loader.js:952:19)
[nodemon] app crashed - waiting for file changes before starting...
```

**Comment by pradel** [comment]
@acomito I fix the issue for the types but can you please paste the rest of the stack for this

```
Error: Cannot find module '@accounts/magic-link'
Require stack:
```

it will be helpful to debug

**Comment by rohit-gohri** [comment]
It's coming from `@accounts/graphql-api`

```
Error: Cannot find module '@accounts/magic-link'
Require stack:
- /project/node_modules/@accounts/graphql-api/lib/modules/accounts-magic-link/index.js
- /project/node_modules/@accounts/graphql-api/lib/modules/accounts/index.js
- /project/node_modules/@accounts/graphql-api/lib/modules/index.js
- /project/node_modules/@accounts/graphql-api/lib/index.js
```

**Comment by zenweasel** [comment]
Seeing the same issue with magic-link being required by `@accounts/graphql-api` but not included in the dependencies. Adding it alongside graphql-api fixed it but shouldn't need to do that since my package doesn't directly require it.

**Comment by acomito** [comment]
@zenweasel can we close this issue based on your PR?

**Comment by pradel** [comment]
@acomito the issue is still there, no pr to fix the issue was opened
