### ISSUE TITLE
Mongo.createUser and Mongo.createSession on Meteor@2.5.1

### ISSUE THREAD

**Issue by awatson1978** [accounts-js/accounts#1250]
# Bug report

Getting the following error on Meteor@2.5.1, which uses Mongo 4.X:

```
W20230507-20:07:34.414(-5)? (STDERR) error TypeError: Cannot read property '0' of undefined
W20230507-20:07:34.414(-5)? (STDERR)     at Mongo.<anonymous> (/Users/awatson/Code/nomex/nomex-app/node_modules/@accounts/mongo/lib/mongo.js:454:54)
W20230507-20:07:34.414(-5)? (STDERR)     at step (/Users/awatson/Code/nomex/nomex-app/node_modules/@accounts/mongo/node_modules/tslib/tslib.js:140:27)
W20230507-20:07:34.414(-5)? (STDERR)     at Object.next (/Users/awatson/Code/nomex/nomex-app/node_modules/@accounts/mongo/node_modules/tslib/tslib.js:121:57)
W20230507-20:07:34.414(-5)? (STDERR)     at fulfilled (/Users/awatson/Code/nomex/nomex-app/node_modules/@accounts/mongo/node_modules/tslib/tslib.js:111:62)
W20230507-20:07:34.415(-5)? (STDERR)     at /Users/awatson/.meteor/packages/promise/.0.12.0.qcz8u8.npe48++os+web.browser+web.browser.legacy+web.cordova/npm/node_modules/meteor-promise/fiber_pool.js:43:40
W20230507-20:07:34.415(-5)? (STDERR)  => awaited here:
W20230507-20:07:34.415(-5)? (STDERR)     at Function.Promise.await (/Users/awatson/.meteor/packages/promise/.0.12.0.qcz8u8.npe48++os+web.browser+web.browser.legacy+web.cordova/npm/node_modules/meteor-promise/promise_server.js:56:12)
W20230507-20:07:34.415(-5)? (STDERR)     at server/AccountsServer.js:1009:24
W20230507-20:07:34.415(-5)? (STDERR)     at /Users/awatson/.meteor/packages/promise/.0.12.0.qcz8u8.npe48++os+web.browser+web.browser.legacy+web.cordova/npm/node_modules/meteor-promise/fiber_pool.js:43:40
W20230507-20:07:34.417(-5)? (STDERR) (node:5433) UnhandledPromiseRejectionWarning: TypeError: Cannot read property '0' of undefined
W20230507-20:07:34.417(-5)? (STDERR)     at Mongo.<anonymous> (/Users/awatson/Code/nomex/nomex-app/node_modules/@accounts/mongo/lib/mongo.js:454:54)
W20230507-20:07:34.418(-5)? (STDERR)     at step (/Users/awatson/Code/nomex/nomex-app/node_modules/@accounts/mongo/node_modules/tslib/tslib.js:140:27)
W20230507-20:07:34.418(-5)? (STDERR)     at Object.next (/Users/awatson/Code/nomex/nomex-app/node_modules/@accounts/mongo/node_modules/tslib/tslib.js:121:57)
W20230507-20:07:34.418(-5)? (STDERR)     at fulfilled (/Users/awatson/Code/nomex/nomex-app/node_modules/@accounts/mongo/node_modules/tslib/tslib.js:111:62)
W20230507-20:07:34.418(-5)? (STDERR)     at /Users/awatson/.meteor/packages/promise/.0.12.0.qcz8u8.npe48++os+web.browser+web.browser.legacy+web.cordova/npm/node_modules/meteor-promise/fiber_pool.js:43:40
W20230507-20:07:34.420(-5)? (STDERR)  => awaited here:
W20230507-20:07:34.421(-5)? (STDERR)     at Function.Promise.await (/Users/awatson/.meteor/packages/promise/.0.12.0.qcz8u8.npe48++os+web.browser+web.browser.legacy+web.cordova/npm/node_modules/meteor-promise/promise_server.js:56:12)
W20230507-20:07:34.421(-5)? (STDERR)     at server/AccountsServer.js:1009:24
W20230507-20:07:34.421(-5)? (STDERR)     at /Users/awatson/.meteor/packages/promise/.0.12.0.qcz8u8.npe48++os+web.browser+web.browser.legacy+web.cordova/npm/node_modules/meteor-promise/fiber_pool.js:43:40
W20230507-20:07:34.421(-5)? (STDERR) (node:5433) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 2)
W20230507-20:07:34.422(-5)? (STDERR) (node:5433) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
```
## Describe the bug

Accounts.js is trying to access `ret.ops[0]._id` when it should be accessing `ret.insertedId`;

## Expected behavior

```
if(Array.isArray(ret.ops)){
  return [2 /*return*/, ret.ops[0]._id.toString()];
} else {
  return [2 /*return*/, ret.insertedId._id.toString()];
}
```

## System information

- @accounts/mongo-password@0.32.4
- @accounts/mongo-sessions@0.33.0
- Meteor@2.5.1
- Mongo 4.X:

**Comment by BStid** [comment]
This fixed my issue! If only we could get it pushed to production.
