### ISSUE TITLE
AccountsServer Mail Configuration Compile Error (Type Error)

### ISSUE THREAD

**Issue by umutyerebakmaz** [accounts-js/accounts#835]
hi friends, this.accountsClientPassword.requestVerificationEmail ('umutyerebakmaz@gmail.com ') on the client side for testing purposes without email configuration; I'm sending a mail verification email. Terminal comes to the following screen. so no problem here for me.

<img width="1409" alt="Ekran Resmi 2019-10-15 15 02 23" src="https://user-images.githubusercontent.com/13598231/66830195-9312f180-ef5d-11e9-828c-7ffd856734ff.png">

This is my AccountsServer document with no email settings.

```typescript
import 'reflect-metadata';
import { MongoClient } from 'mongodb';
import { AccountsServer } from '@accounts/server';
import { AccountsPassword } from '@accounts/password';
import AccountsMongoDB from '@accounts/mongo';
import { ApolloServer, attachDirectiveResolvers } from 'apollo-server';
import { AppModule } from '@modules/app/app.module';
import * as dotenv from "dotenv";
dotenv.config();

const PORT = process.env['PORT'];
const MONGO_URI = process.env['MONGO_URI'];
const TOKEN_SECRET = process.env['TOKEN_SECRET'];

async function main() {
    console.time('Bootstrap');
    const mongoClient = await MongoClient.connect(MONGO_URI, { useNewUrlParser: true, useUnifiedTopology: true });
    const db = mongoClient.db();

    // Create accounts server that holds a lower level of all accounts operations
    const accountsServer = new AccountsServer(
        {
            db: new AccountsMongoDB(db),
            tokenSecret: TOKEN_SECRET
        },
        {
            password: new AccountsPassword({
                // This option is called when a new user create an account
                // Inside we can apply our logic to validate the user fields
                validateNewUser: user => {
                    if (user.profile.fullname.length < 2) {
                        throw new Error('Ad Soyad çok kısa');
                    }
                    return user;
                },
            }),
        }
    );

    const { schema } = AppModule.forRoot({
        accountsServer,
        db
    });

    attachDirectiveResolvers(schema, {
        id: (_, { _id }) => _id.toString(),
    });

    const apolloServer = new ApolloServer({
        schema,
        playground: true,
        introspection: true,
        context: session => session,
    });

    const { url } = await apolloServer.listen(PORT);
    console.info(`Server listening: ${url}`);
    console.timeEnd('Bootstrap');
}

main();

```

Now let's get to the email configuration. In the documentation, the email configuration is said to be done in the same way.

```typescript
    const options = {
        // You can handle sending the emails by providing an optional sendMail function
        sendMail: ({ from: 'no-reply@kitaphub.com', subject: 'subject', to: 'umutyerebakmaz@gmail.com', text: 'text', html: '<div>example</div>' }): Promise<void>;
    };
```
When I add the necessary parameters for Mail, the final version of Accounts Server looks like this.

```typescript
import 'reflect-metadata';
import { MongoClient } from 'mongodb';
import { AccountsServer } from '@accounts/server';
import { AccountsPassword } from '@accounts/password';
import AccountsMongoDB from '@accounts/mongo';
import { ApolloServer, attachDirectiveResolvers } from 'apollo-server';
import { AppModule } from '@modules/app/app.module';
import * as dotenv from "dotenv";
dotenv.config();

const PORT = process.env['PORT'];
const MONGO_URI = process.env['MONGO_URI'];
const TOKEN_SECRET = process.env['TOKEN_SECRET'];

async function main() {
    console.time('Bootstrap');
    const mongoClient = await MongoClient.connect(MONGO_URI, { useNewUrlParser: true, useUnifiedTopology: true });
    const db = mongoClient.db();

    // Options for AccountsServer
    const options = {
        // You can handle sending the emails by providing an optional sendMail function
        sendMail: ({ from: 'no-reply@kitaphub.com', subject: 'subject', to: 'umutyerebakmaz@gmail.com', text: 'text', html: '<div>example</div>' }): Promise<void>;
    };

    // Create accounts server that holds a lower level of all accounts operations
    const accountsServer = new AccountsServer(
        {
            db: new AccountsMongoDB(db),
            tokenSecret: TOKEN_SECRET,
            sendMail: options.sendMail,
        },
        {
            password: new AccountsPassword({
                // This option is called when a new user create an account
                // Inside we can apply our logic to validate the user fields
                validateNewUser: user => {
                    if (user.profile.fullname.length < 2) {
                        throw new Error('Ad Soyad çok kısa');
                    }
                    return user;
                },
            }),
        }
    );

    const { schema } = AppModule.forRoot({
        accountsServer,
        db
    });

    attachDirectiveResolvers(schema, {
        id: (_, { _id }) => _id.toString(),
    });

    const apolloServer = new ApolloServer({
        schema,
        playground: true,
        introspection: true,
        context: session => session,
    });

    const { url } = await apolloServer.listen(PORT);
    console.info(`Server listening: ${url}`);
    console.timeEnd('Bootstrap');
}

main();
```

My application gives compile error for type error. I couldn't fix what I did. Can you help me please.
<img width="1552" alt="Ekran Resmi 2019-10-15 15 17 58" src="https://user-images.githubusercontent.com/13598231/66830794-0406d900-ef5f-11e9-8c24-e33ce7a7515d.png">
<img width="1550" alt="Ekran Resmi 2019-10-15 15 17 31" src="https://user-images.githubusercontent.com/13598231/66830813-0b2de700-ef5f-11e9-9af4-76fd67670f90.png">

**Comment by pradel** [comment]
Hey, well currently you are passing the signature of the function as an option to sendMail. What you have to do is to actually handle the email that will be sent, basically this function will be called every time the server has to send an email.
Please check the documentation to see how to configure it with your email framework :)
https://accounts-js.netlify.com/docs/email

**Comment by ardatan** [comment]
https://accounts-js.netlify.com/docs/email/#example-using-nodemailer
You need to use an email implementation like here. First line is wrong in this example by the way but assume that it is `import nodemailer from 'nodemailer';`.

**Comment by umutyerebakmaz** [comment]
```typescript
import 'reflect-metadata';
import { MongoClient } from 'mongodb';
import { AccountsServer } from '@accounts/server';
import { AccountsPassword } from '@accounts/password';
import AccountsMongoDB from '@accounts/mongo';
import { ApolloServer, attachDirectiveResolvers } from 'apollo-server';
import { AppModule } from '@modules/app/app.module';
import * as dotenv from "dotenv";
dotenv.config();
import nodemailer from 'nodemailer';

// mongo
const PORT = process.env['PORT'];
const MONGO_URI = process.env['MONGO_URI'];
const TOKEN_SECRET = process.env['TOKEN_SECRET'];
// mail
const MAIL_HOST = process.env['MAIL_HOST'];
const MAIL_PORT = process.env['MAIL_PORT'];
const MAIL_USER = process.env['MAIL_USER'];
const MAIL_PASSWORD = process.env['MAIL_PASSWORD']

async function main() {
    console.time('Bootstrap');
    const mongoClient = await MongoClient.connect(MONGO_URI, { useNewUrlParser: true, useUnifiedTopology: true });
    const db = mongoClient.db();

    // Initiate nodemailer
    const transporter = nodemailer.createTransport(
        {
            host: 'smtp.mailgun.org',
            port: 587,
            secure: false, // true for 465, false for other ports
            auth: {
                user: MAIL_USER,
                pass: MAIL_PASSWORD
            }
        }
    );

    // Options for AccountsServer
    const options = {
        sendMail: async ({ from, subject, to, text, html }) => {
            await transporter.sendMail(
                {
                    from: '"KITAPHUB 👻" <noreply@kitaphub.com>', // sender address
                    to: 'umutyerebakmaz@gmail.com, umutyerebakmaz@hotmail.com', // list of receivers
                    subject: 'Hello ✔', // Subject line
                    text: 'Hello world?', // plain text body
                    html: '<b>Hello world?</b>' // html body
                }
            );
        },
    };
    // AccountsServer
    const accountsServer = new AccountsServer(
        {
            db: new AccountsMongoDB(db),
            tokenSecret: TOKEN_SECRET,
            sendMail: options.sendMail
        },
        {
            password: new AccountsPassword({
                // This option is called when a new user creates an account
                // Inside we can apply our logic to validate the user fields
                validateNewUser: user => {
                    if (user.profile.fullname.length < 2) {
                        throw new Error('Ad Soyad çok kısa');
                    }
                    return user;
                },
            }),
        }
    );

    const { schema } = AppModule.forRoot({
        accountsServer,
        db
    });

    attachDirectiveResolvers(schema, {
        id: (_, { _id }) => _id.toString(),
    });

    const apolloServer = new ApolloServer({
        schema,
        playground: true,
        introspection: true,
        context: session => session,
    });

    const { url } = await apolloServer.listen(PORT);
    console.info(`Server listening: ${url}`);
    console.timeEnd('Bootstrap');
}

main();
```

This time, everything has to be fine. Still didn't.

<img width="1550" alt="Ekran Resmi 2019-10-16 12 25 50" src="https://user-images.githubusercontent.com/13598231/66906361-3cb2bb00-f010-11e9-9d99-6d22506dccdf.png">

`console
(node:56890) UnhandledPromiseRejectionWarning: TypeError: Cannot read property 'createTransport' of undefined
[1]     at main (/Users/umut/Sites/kitaphub/server/src/index.ts:28:36)
[1]     at process._tickCallback (internal/process/next_tick.js:68:7)
[1] (node:56890) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
[1] (node:56890) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.

`

**Comment by umutyerebakmaz** [comment]
```typescript 
main().catch(console.err);
```
 TypeError: Cannot read property 'createTransport' of undefined
[1]  at main (/Users/umut/Sites/kitaphub/server/src/index.ts:28:42)
[1]  at process._tickCallback (internal/process/next_tick.js:68:

**I also added the catch block this time I get this error.**

<img width="1550" alt="Ekran Resmi 2019-10-16 12 36 49" src="https://user-images.githubusercontent.com/13598231/66907323-d2027f00-f011-11e9-9fbd-f345f609aaca.png">
