### ISSUE TITLE
Error: Union type ChallengeResult can only include Object types, it cannot include Boolean.

### ISSUE THREAD

**Issue by mrvictorn** [accounts-js/accounts#962]
# Bug report

Simple code fails with  `Error: Union type ChallengeResult can only include Object types, it cannot include Boolean.`

ChallengeResult is mentioned at accounts-mfa, which is not directly used at sample code

## Describe the bug
During app launch, error is thrown with stack trace:
`Type "ChallengeResult" is missing a "__resolveType" resolver. Pass false into "resolverValidationOptions.requireResolversForResolveType" to disable this warning.
Type "AuthenticationResult" is missing a "__resolveType" resolver. Pass false into "resolverValidationOptions.requireResolversForResolveType" to disable this warning.
(node:16912) UnhandledPromiseRejectionWarning: Error: Union type ChallengeResult can only include Object types, it cannot include Boolean.
    at assertValidSchema (/Users/viktor/Documents/dev/customers/iCorn/icorn-backend-gql/node_modules/graphql/type/validate.js:71:11)
    at assertValidExecutionArguments (/Users/viktor/Documents/dev/customers/iCorn/icorn-backend-gql/node_modules/graphql/execution/execute.js:136:35)
    at executeImpl (/Users/viktor/Documents/dev/customers/iCorn/icorn-backend-gql/node_modules/graphql/execution/execute.js:86:3)
    at Object.execute (/Users/viktor/Documents/dev/customers/iCorn/icorn-backend-gql/node_modules/graphql/execution/execute.js:64:63)
    at Object.generateSchemaHash (/Users/viktor/Documents/dev/customers/iCorn/icorn-backend-gql/node_modules/apollo-server-core/src/utils/schemaHash.ts:11:18)
    at ApolloServer.generateSchemaDerivedData (/Users/viktor/Documents/dev/customers/iCorn/icorn-backend-gql/node_modules/apollo-server-core/src/ApolloServer.ts:522:24)
    at new ApolloServerBase (/Users/viktor/Documents/dev/customers/iCorn/icorn-backend-gql/node_modules/apollo-server-core/src/ApolloServer.ts:381:32)
    at new ApolloServer (/Users/viktor/Documents/dev/customers/iCorn/icorn-backend-gql/node_modules/apollo-server-express/src/ApolloServer.ts:88:5)
    at new ApolloServer (/Users/viktor/Documents/dev/customers/iCorn/icorn-backend-gql/node_modules/apollo-server/src/index.ts:36:5)
    at start (/Users/viktor/Documents/dev/customers/iCorn/icorn-backend-gql/index.js:111:18)
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
`

## To Reproduce
```
const { authenticated, accountsBoost } = require('@accounts/boost')
const { mergeTypeDefs, mergeResolvers } = require('graphql-toolkit')
const { ApolloServer } = require('apollo-server')

const start = async () => {
  const accounts = (
    await accountsBoost({
      tokenSecret: 'terrible secret',
    })
  ).graphql()

  const typeDefs = `
    type PrivateType @auth {
      privateField: String
    }
    type Query {
      publicField: String
      privateField: String @auth
      privateType: PrivateType
      privateFieldWithAuthResolver: String
    }
    type Mutation {
      privateMutation: String @auth
      publicMutation: String
    }
    `

  const resolvers = {
    PrivateType: {
      privateField: () => 'private',
    },
    Query: {
      publicField: () => 'public',
      privateField: () => 'private',
      privateType: () => '',
      privateFieldWithAuthResolver: authenticated((root, args, context) => {
        return 'private'
      }),
    },
    Mutation: {
      privateMutation: () => 'private',
      publicMutation: () => 'public',
    },
  }

  const apolloServer = new ApolloServer({
    typeDefs: mergeTypeDefs([typeDefs, accounts.typeDefs]),
    resolvers: mergeResolvers([accounts.resolvers, resolvers]),
    schemaDirectives: {
      // In order for the `@auth` directive to work
      ...accounts.schemaDirectives,
    },
    context: ({ req }) => accounts.context({ req }),
  })
    .listen()
    .then((res) => {
      console.log(`GraphQL server running at ${res.url}`)
    })
}

start()
```

## Expected behavior

Should just work

## System information

Version of accounts-js: 0.26.0-alpha.3

**Comment by pradel** [comment]
Hey @mrvictorn, the alpha version is not ready :) can you use the latest stable version for now please?
